project_name: deepfake_watermark
epochs: 14
batch_size: 16
lr: 5e-4
image_size: 128
message_length: 30
message_range: 1
wm_factor: 0.03
device: "cuda:0"
lpips_w: 1
encoder_w: 3
ssim_w: 4
all_w: 5
df_w: 4
common_w: 5
perturb_w: 1
perturb_w1: 1
diff_w: 1
dataset_path: E:/scpcode/CelebAMask-HQ/processed/128
saved_images_number: 4
wm_channels: 4
